name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
          bun-version: 1.0.22
    - name: Install dependencies
      run:  bun install
    - name: Install Playwright Browsers
      run:  bunx playwright install --with-deps
    - name: Run Playwright tests
      env: 
        CI: ${{ secrets.CI }}
        NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
        NEXT_PUBLIC_APP_PORT: ${{ secrets.NEXT_PUBLIC_APP_PORT }}
      run:  bunx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
